redo

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -356,64 +356,64 @@ jobs:
                       FRONTEND_URL=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-${AWS_DEFAULT_REGION}.amazonaws.com
                       if curl -s $FRONTEND_URL | grep "Welcome"
                       then
-                        exit 0
+                        exit 1
                       else
                         exit 1
                       fi
             - destroy-environment
             - revert-migrations
 
-    cloudfront-update:
-        docker:
-            - image: cimg/base:stable
-        steps:
-            - checkout
-            - install_awscli
-            - install_nodejs
-            - run:
-                  name: Update cloudfront distribution
-                  command: |
-                      aws cloudformation deploy \
-                      --template-file .circleci/files/cloudfront.yml \
-                      --stack-name InitialStack \
-                      --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
-                      --tags project=udapeople
-            - run:
-                  name: Save old Workflow_ID
-                  command: |
-                      export OLD_WORKFLOW_ID=$(aws cloudformation \
-                              list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
-                              --no-paginate --output text)
-                      echo "Old Workflow ID: $OLD_WORKFLOW_ID"
-                      curl https://kvdb.io/CJhzGNYEFHWL71z3PVjMum/old_workflow_id -d "${OLD_WORKFLOW_ID}"
+    # cloudfront-update:
+    #     docker:
+    #         - image: cimg/base:stable
+    #     steps:
+    #         - checkout
+    #         - install_awscli
+    #         - install_nodejs
+    #         - run:
+    #               name: Update cloudfront distribution
+    #               command: |
+    #                   aws cloudformation deploy \
+    #                   --template-file .circleci/files/cloudfront.yml \
+    #                   --stack-name InitialStack \
+    #                   --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
+    #                   --tags project=udapeople
+    #         - run:
+    #               name: Save old Workflow_ID
+    #               command: |
+    #                   export OLD_WORKFLOW_ID=$(aws cloudformation \
+    #                           list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+    #                           --no-paginate --output text)
+    #                   echo "Old Workflow ID: $OLD_WORKFLOW_ID"
+    #                   curl https://kvdb.io/CJhzGNYEFHWL71z3PVjMum/old_workflow_id -d "${OLD_WORKFLOW_ID}"
 
-                      echo old worklow id: '${OLD_WORKFLOW_ID}'
-                      echo curent worklow id: '${CIRCLE_WORKFLOW_ID}'
-            - destroy-environment
-            - revert-migrations
+    #                   echo old worklow id: '${OLD_WORKFLOW_ID}'
+    #                   echo curent worklow id: '${CIRCLE_WORKFLOW_ID}'
+    #         - destroy-environment
+    #         - revert-migrations
 
-    cleanup:
-        docker:
-            - image: cimg/base:stable
-        steps:
-            - checkout
-            - install_awscli
-            - install_nodejs
-            - run:
-                  name: Remove old stacks and files
-                  command: |
-                      export OldWorkflowID=$(curl --insecure https://kvdb.io/CJhzGNYEFHWL71z3PVjMum/old_workflow_id)
-                      echo Old Workflow ID: $OldWorkflowID
-                      echo CIRCLE_WORKFLOW_ID "${CIRCLE_WORKFLOW_ID:0:7}"
-                      if [[ "${CIRCLE_WORKFLOW_ID:0:7}" == "${OldWorkflowID}" ]]
-                      then
-                      echo '--Delete confirm--'
-                      aws s3 rm s3://udapeople-${OldWorkflowID} --recursive
-                      aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
-                      aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
-                      else
-                      echo '--Cannot cleanup--'
-                      fi
+    # cleanup:
+    #     docker:
+    #         - image: cimg/base:stable
+    #     steps:
+    #         - checkout
+    #         - install_awscli
+    #         - install_nodejs
+    #         - run:
+    #               name: Remove old stacks and files
+    #               command: |
+    #                   export OldWorkflowID=$(curl --insecure https://kvdb.io/CJhzGNYEFHWL71z3PVjMum/old_workflow_id)
+    #                   echo Old Workflow ID: $OldWorkflowID
+    #                   echo CIRCLE_WORKFLOW_ID "${CIRCLE_WORKFLOW_ID:0:7}"
+    #                   if [[ "${CIRCLE_WORKFLOW_ID:0:7}" == "${OldWorkflowID}" ]]
+    #                   then
+    #                   echo '--Delete confirm--'
+    #                   aws s3 rm s3://udapeople-${OldWorkflowID} --recursive
+    #                   aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
+    #                   aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
+    #                   else
+    #                   echo '--Cannot cleanup--'
+    #                   fi
     notify_on_success:
         docker:
             - image: cimg/base:stable
@@ -452,10 +452,10 @@ workflows:
                   requires: [run-migrations]
             - smoke-test:
                   requires: [deploy-backend, deploy-frontend]
-            - cloudfront-update:
-                  requires: [smoke-test]
-            - cleanup:
-                  requires: [cloudfront-update]
+            # - cloudfront-update:
+            #       requires: [smoke-test]
+            # - cleanup:
+            #       requires: [cloudfront-update]
             - notify_on_success:
                   requires:
                       - test-frontend
